### PR TITLE
force encoding for source host

### PR DESCRIPTION
**Pull request by gmoskovicz**
Running tests on windows showed that potentially the encoding for the source host could come with Windows Encoding rather than UTF 8, which caused the configuration to fail.

### CODE REVIEW

**Comment by gmoskovicz** [comment]
Fixes #22

**Comment by gmoskovicz** [comment]
@ph @purbon @jsvd Can i have a review?

**Comment by jsvd** [comment]
The fix does solve the problem but I'm trying to find out why https://github.com/elastic/logstash/blob/master/lib/logstash/patches/bugfix_jruby_2558.rb doesn't fix this in the first place, since it was added to core because of this problem: some of the strings windows produces aren't UTF8
If I can't find a proper fix soon at the core level we can just merge this.

**Comment by gmoskovicz** [comment]
@jsvd makes sense to me!

**Comment by jsvd** [comment]
Apparently the encoding issue on windows still exists in jruby 1.7.22: https://github.com/jruby/jruby/issues/2558#issuecomment-151102656

The proper way to address this would be through extending the monkeypatch we do in core to process all output of IPSocket.recvfrom calls, but since we have frozen logstash-core, I'll open an issue and let this in :)

LGTM

**Comment by jsvd** [comment]
merged in 8b003fe7f2386ab67e1f62f9e7fe4aa5b994cb4c 604c42cb69e1c53467c2f0a22a69429c88b95a46

**Pull request closed without merging**
