### PR TITLE
Use float instead of integer for timestamp parsing to preserve sub-second precision

### PR DESCRIPTION
**Pull request by bobrik**

### CODE REVIEW

**Comment by jordansissel** [comment]
Is this related to #32?

**Comment by rikwasmus** [comment]
Fixes same problem (#30 as well BTW) , BigDecimal.frac() might be conserving more precision than casting to float.

**Comment by bobrik** [comment]
Yes, it's the same thing with simpler code.

**Comment by colinsurprenant** [comment]
I suggest we adopt #32 with my proposed modifications.

**Comment by colinsurprenant** [comment]
Thanks @bobrik for your contribution. I will close this PR, the fix in in #35.

**Comment by bobrik** [comment]
:+1:

**Pull request closed without merging**
